### ISSUE TITLE
0 cells detected in each spot -- cell detection script.

### ISSUE THREAD

**Issue by ajitashree** [szczurek-lab/Celloscope#2]
Dear authors, 

We are running your method Celloscope for spot-deconvolution task. However, we are running into issues in preliminary steps i.e. in the cells counting procedure. 

**We are getting 0 cells in each spot as output. We have also raised an issue on qupath_spot_utils github from your lab. More details on the error is available in the issue raised here https://github.com/szczurek-lab/qupath-spot-utils/issues/1.**

We would greatly appreciate your help in  running the method

Thanks,
Ajita Shree

**Comment by gerasa** [comment]
Dear Ajita,
thank you for your interest in Celloscope. I will let know the author of the cell counting procedure about the issue you raised here:
https://github.com/szczurek-lab/qupath-spot-utils/issues/1

Best,
Agnieszka

**Comment by ajitashree** [comment]
Thanks Agnieszka, we will follow the suggestions made on qupath-spot-utils github.
